export class BankVo {
  constructor(
    public name:string,
    public label:string,
    public icon:string
  ) { }
}

export const BankList:BankVo[] = [
  new BankVo('AASEN_SB', 'Aasen Sparebank', 'aasen.png'),
  new BankVo('AKADEMIKERNE_DANSKE', 'Akademikerne (Danske Bank)', 'danske.png'),
  new BankVo('ANDEBU_SB', 'Andebu Sparebank', 'andebu.png'),
  new BankVo('ARENDAL_SK', 'Arendal og Omegns Sparekasse', 'Arendal.png'),
  new BankVo('ASKIM_SB', 'Askim og Spydeberg Sparebank', 'askim.png'),
  new BankVo('AURLAND_SB', 'Aurland Sparebank', 'aurland.jpg'),
  new BankVo('AURSKOG_SB', 'Aurskog Sparebank', null),
  new BankVo('BN_BANK', 'BN Bank ASA', null),
  new BankVo('BANK2', 'Bank2 ASA', null),
  new BankVo('BERG_SB', 'Berg Sparebank', null),
  new BankVo('BIEN', 'Bien Sparebank ASA', null),
  new BankVo('BIRKENES_SB', 'Birkenes Sparebank', null),
  new BankVo('BJUGN_SB', 'Bjugn Sparebank', null),
  new BankVo('BLAKER_SB', 'Blaker Sparebank', null),
  new BankVo('BOLIGKREDITT', 'Boligkreditt.no (Sparebanken Øst Boligkreditt AS)', null),
  new BankVo('BULDER', 'Bulder Bank (Sparebanken Vest)', null),
  new BankVo('CULTURA', 'Cultura Sparebank', null),
  new BankVo('DANSKE_BANK', 'Danske Bank', null),
  new BankVo('DIN_BANK', 'Din Bank (Sparebanken Øst)', null),
  new BankVo('DNB', 'DNB Bank ASA', 'dnb.png'),
  new BankVo('DRANGEDAL_SB', 'Drangedal Sparebank', null),
  new BankVo('EIDSBERG_SB', 'Eidsberg Sparebank', null),
  new BankVo('ETNE_SB', 'Etne Sparebank', null),
  new BankVo('ETNEDAL_SB', 'Etnedal Sparebank', null),
  new BankVo('EVJE_SB', 'Evje og Hornnes Sparebank', null),
  new BankVo('FANA_SB', 'Fana Sparebank', null),
  new BankVo('FLEKKEFJORD_SB', 'Flekkefjord Sparebank', null),
  new BankVo('FORNEBU_SB', 'Fornebu Sparebank', null),
  new BankVo('GILDESKAL_SB', 'Gildeskål Sparebank', null),
  new BankVo('GJENSIDIGE_BANK', 'Gjensidige Bank', null),
  new BankVo('GRONG_SB', 'Grong Sparebank', null),
  new BankVo('GRUE_SB', 'Grue Sparebank', null),
  new BankVo('HALTDALEN_SB', 'Haltdalen Sparebank', null),
  new BankVo('HANDELSBANKEN', 'Handelsbanken NUF', null),
  new BankVo('HARSTAD_SB', 'Harstad Sparebank', null),
  new BankVo('HAUGESUND_SB', 'Haugesund Sparebank', null),
  new BankVo('HEGRA_SB', 'Hegra Sparebank', null),
  new BankVo('HELGELAND_SB', 'Helgeland Sparebank', null),
  new BankVo('HEMNE_SB', 'Hemne Sparebank', null),
  new BankVo('HJARTDAL_SB', 'Hjartdal og Gransherad Sparebank', null),
  new BankVo('HJELMELAND_SB', 'Hjelmeland Sparebank', null),
  new BankVo('HOLAND_SB', 'Høland og Setskog Sparebank', null),
  new BankVo('HONEFOSS_SB', 'Hønefoss Sparebank', null),
  new BankVo('INDRE_SOGN_SB', 'Indre Sogn Sparebank', null),
  new BankVo('JERNBANEPERSONALETS', 'Jernbanepersonalets Bank og Forsikring', null),
  new BankVo('JAEREN_SB', 'Jæren Sparebank', null),
  new BankVo('KLP', 'KLP Banken AS', null),
  new BankVo('KRAFTBANK', 'Kraft Bank ASA', null),
  new BankVo('KVINESDAL_SB', 'Kvinesdal Sparebank', null),
  new BankVo('LANDKREDITT', 'Landkreditt Bank AS', null),
  new BankVo('LARVIKBANKEN', 'Larvikbanken', null),
  new BankVo('LILLESANDS_SB', 'Lillesands Sparebank', null),
  new BankVo('LILLESTROMBANKEN', 'LillestrømBanken', null),
  new BankVo('LUSTER_SB', 'Luster Sparebank', null),
  new BankVo('MARKER_SB', 'Marker Sparebank', null),
  new BankVo('MELHUSBANKEN', 'Melhusbanken', null),
  new BankVo('NAL', 'NAL (Gjensidige Bank)', null),
  new BankVo('NORDAX', 'Nordax Bank AB (publ)', null),
  new BankVo('NORDEA', 'NORDEA BANK ABP, FILIAL I NORGE', 'nordea.png'),
  new BankVo('NORDIREKTEBANK', 'NORDirektebank (Skagerrak Sparebank)', null),
  new BankVo('NIDAROS_SB', 'Nidaros Sparebank', null),
  new BankVo('SYKEPLEIERFORBUND_DNB', 'Norsk Sykepleierforbund (DNB)', null),
  new BankVo('NYBYGGER', 'Nybygger.no (Sparebanken Øst)', null),
  new BankVo('OBOS_BANKEN', 'OBOS-banken AS', null),
  new BankVo('OFOTEN_SB', 'Ofoten Sparebank', null),
  new BankVo('ODAL_SB', 'Odal Sparebank', null),
  new BankVo('OPPDALSBANKEN', 'Oppdalsbanken', null),
  new BankVo('ORKLA_SB', 'Orkla Sparebank', null),
  new BankVo('ORLAND_SB', 'Ørland Sparebank', null),
  new BankVo('OSLO_PENSJON', 'Oslo Pensjonsforsikring AS', null),
  new BankVo('OSTRE_AGDER_SB', 'Østre Agder Sparebank', null),
  new BankVo('RINDAL_SB', 'Rindal Sparebank', null),
  new BankVo('ROMSDAL_SB', 'Romsdal Sparebank', null),
  new BankVo('ROROS', 'Rørosbanken', null),
  new BankVo('SANDNES_SB', 'Sandnes Sparebank', null),
  new BankVo('SBANKEN', 'Sbanken ASA', null),
  new BankVo('SELBU_SB', 'Selbu Sparebank', null),
  new BankVo('SKAGERRAK_SB', 'Skagerrak Sparebank', null),
  new BankVo('SKUDENES_SB', 'Skudenes & Aakra Sparebank', null),
  new BankVo('SKUE_SB', 'Skue Sparebank', null),
  new BankVo('SOGN', 'Sogn Sparebank', null),
  new BankVo('SPAREBANKEN_DIN', 'Sparebanken DIN', null),
  new BankVo('SPAREBANKEN_OST', 'Sparebanken Øst', null),
  new BankVo('SPAREBANK_1_BV', 'SpareBank 1 BV', null),
  new BankVo('SPAREBANK_1_GUDBRANDSDAL', 'SpareBank 1 Gudbrandsdal', null),
  new BankVo('SPAREBANK_1_HALLINGDAL_VALDRES', 'SpareBank 1 Hallingdal Valdres', null),
  new BankVo('SPAREBANK_1_LOM_OG_SKJAK', 'SpareBank 1 Lom og Skjåk', null),
  new BankVo('SPAREBANK_1_MODUM', 'SpareBank 1 Modum', null),
  new BankVo('SPAREBANK_1_NORD_NORGE', 'SpareBank 1 Nord-Norge', null),
  new BankVo('SPAREBANK_1_NORDVEST', 'SpareBank 1 Nordvest', null),
  new BankVo('SPAREBANK_1_RINGERIKE_HADELAND', 'SpareBank 1 Ringerike Hadeland', null),
  new BankVo('SPAREBANK_1_SMN', 'SpareBank 1 SMN', null),
  new BankVo('SPAREBANK_1_SR_BANK', 'SpareBank 1 SR-Bank', null),
  new BankVo('SPAREBANK_1_SORE_SUNNMORE', 'SpareBank 1 Søre Sunnmøre', null),
  new BankVo('SPAREBANK_1_TELEMARK', 'SpareBank 1 Telemark', null),
  new BankVo('SPAREBANK_1_OSTFOLD_AKERSHUS', 'SpareBank 1 Østfold Akershus', null),
  new BankVo('SPAREBANK_1_OSTLANDET', 'SpareBank 1 Østlandet', null),
  new BankVo('SB_MORE', 'Sparebanken Møre', null),
  new BankVo('SB_NARVIK', 'Sparebanken Narvik', null),
  new BankVo('SB_SOGNFJORDANE', 'Sparebanken Sogn og Fjordane', null),
  new BankVo('SB_SOR', 'Sparebanken Sør', null),
  new BankVo('SB_VEST', 'Sparebanken Vest', null),
  new BankVo('SOKNEDAL_SB', 'Soknedal Sparebank', null),
  new BankVo('SPAREBANK_68', 'Sparebank 68° Nord', null),
  new BankVo('SPARESKILLINGSBANKEN', 'Spareskillingsbanken', null),
  new BankVo('STATENS_PENSJONSKASSE', 'Statens pensjonskasse', null),
  new BankVo('STROMMEN_SB', 'Strømmen Sparebank', null),
  new BankVo('SUNNDAL_SB', 'Sunndal Sparebank', null),
  new BankVo('SURNADAL_SB', 'Surnadal Sparebank', null),
  new BankVo('STADSBYGD_SB', 'Stadsbygd Sparebank', null),
  new BankVo('STOREBRAND', 'Storebrand Bank ASA', null),
  new BankVo('SOGNE_SB', 'Søgne og Greipstad Sparebank', null),
  new BankVo('TOLGA_SB', 'Tolga-Os Sparebank', null),
  new BankVo('TOTENS_SB', 'Totens Sparebank', null),
  new BankVo('TROGSTAD_SB', 'Trøgstad Sparebank', null),
  new BankVo('TYSNES_SB', 'Tysnes Sparebank', null),
  new BankVo('VALDRES_SB', 'Valdres Sparebank', null),
  new BankVo('VALLE_SB', 'Valle Sparebank', null),
  new BankVo('VEKSELBANKEN', 'Vekselbanken', null),
  new BankVo('VIK_SB', 'Vik Sparebank', null),
  new BankVo('VOSS_SB', 'Voss Sparebank', null),
  new BankVo('YS_GJENSIDIGE', 'YS (Gjensidige Bank)', null),
  new BankVo('AFJORD_SB', 'Åfjord Sparebank', null),
  new BankVo('ORSKOG_SB', 'Ørskog Sparebank', null),
];

