export class BankVo {
  constructor(
    public name: string,
    public label: string,
    public icon: string,
    public logo: string | null,
    public loginWithSsn: boolean = false,
    public isEikaBank: boolean = false,
    public isSb1Bank: boolean = false,
    public isMissing: boolean = false,
    public isTinkBank: boolean = false,
    public hasFixedLoans: boolean = false,
    public isSigniCat: boolean = false,
    public hasFixedPrice: boolean = false,
    public hasSubMembership = false,
    public isDSSBank = false,
    public mobileUrl: string | null = null
  ) {}
}

export const eikaBanks: BankVo[] = [
  new BankVo(
    'AASEN_SB',
    'Aasen Sparebank',
    'aasen.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://aasen-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'ANDEBU_SB',
    'Andebu Sparebank',
    'andebu.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://andebu-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'AKADEMIKERNE_DANSKE',
    'Akademikerne Danske',
    'danske.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    'https://www.danskebank.no/nb-no/Privat/Nettbank-og-Mobil/nettbank/support/Pages/ofte-stilte-sporsmal.aspx#'
  ),
  new BankVo(
    'ARENDAL_SK',
    'Arendal og Omegns Sparekasse',
    'sparekassa_arendal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://sparekassa.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'ARENDAL_SK',
    'Sparekassa',
    'sparekassa_arendal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://sparekassa.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'ASKIM_SB',
    'Askim og Spydeberg Sparebank',
    'askim.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://asbank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'AURSKOG_SB',
    'Aurskog Sparebank',
    'aurskog.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://aurskog-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'BANK2',
    'Bank2 ASA',
    'bank2.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://bank2.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'BERG_SB',
    'Berg Sparebank',
    'berg.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://berg-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'BIEN',
    'Bien Sparebank ASA',
    'bien.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://bien.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'BIRKENES_SB',
    'Birkenes Sparebank',
    'birkenes.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://birkenes-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'BJUGN_SB',
    'Bjugn Sparebank',
    'bjugn.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://bjugn-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'BLAKER_SB',
    'Blaker Sparebank',
    'blaker.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://blakersparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'DRANGEDAL_SB',
    'Drangedal Sparebank',
    'drangedal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://drangedalsparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'EIDSBERG_SB',
    'Eidsberg Sparebank',
    'eidsberg.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://esbank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'ETNEDAL_SB',
    'Etnedal Sparebank',
    'etnedal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://etnedalsparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'EVJE_SB',
    'Evje og Hornnes Sparebank',
    'evje_hornnes.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://eh-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'FORNEBU_SB',
    'Fornebu Sparebank',
    'fornebu.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://fornebusparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'GILDESKAL_SB',
    'Gildeskål Sparebank',
    'gildeskal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://gildeskaal-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'GRONG_SB',
    'Grong Sparebank',
    'grong.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://grong-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'GRUE_SB',
    'Grue Sparebank',
    'grue.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://gruesparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'HALTDALEN_SB',
    'Haltdalen Sparebank',
    'haltdalen.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://haltdalensparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'HEGRA_SB',
    'Hegra Sparebank',
    'hegra.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://hegrasparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'HEMNE_SB',
    'Hemne Sparebank',
    'hemne.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://hemnesparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'HIMLA_FANA_SB',
    'Himla (Fana Sparebank)',
    'himla.png',
    null,
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    'https://www.himla.no/banktjenester/boliglan/?utm_source=renteradar.no&utm_medium=nettside&utm_campaign=ta_kontakt_for_samarbeid'
  ),
  new BankVo(
    'HJARTDAL_SB',
    'Hjartdal og Gransherad Sparebank',
    'hjartdal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://hjartdalbanken.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'HJELMELAND_SB',
    'Hjelmeland Sparebank',
    'hjelmeland.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://hjelmeland-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'HOLAND_SB',
    'Høland og Setskog Sparebank',
    'holand_setskog.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://hsbank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'JERNBANEPERSONALETS',
    'Jernbanepersonalets Bank og Forsikring',
    'jernbane.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://jbf.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'JAEREN_SB',
    'Jæren Sparebank',
    'jaeren.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://jaerensparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'KVINESDAL_SB',
    'Kvinesdal Sparebank',
    'kvinesdal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://kvinesdalsparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'LARVIKBANKEN',
    'Larvikbanken',
    'larvikbanken.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://larvikbanken.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'LILLESTROMBANKEN',
    'LillestrømBanken',
    'lillestrom.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://lillestrombanken.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'MARKER_SB',
    'Marker Sparebank',
    'marker.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://marker-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'MELHUSBANKEN',
    'Melhusbanken',
    'melhus.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://melhusbanken.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'NIDAROS_SB',
    'Nidaros Sparebank',
    'nidaros.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://nidaros-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'NORDIREKTEBANK',
    'NORDirektebank (Skagerrak Sparebank)',
    'nordirektebank.png',
    null,
    true,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    false,
    'https://nordirektebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'MY_BANK',
    'MYBANK ASA',
    'mybank.png',
    null,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    ''
  ),
  new BankVo(
    'BLUESTEP_BANK',
    'Bluestep Bank',
    'bluestep.png',
    null,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    ''
  ),
  new BankVo(
    'INSTA_BANK',
    'Instabank',
    'instabank.png',
    null,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    ''
  ),
  new BankVo(
    'ODAL_SB',
    'Odal Sparebank',
    'odal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://odal-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'OPPDALSBANKEN',
    'Oppdalsbanken',
    'oppdalsbanken.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://oppdalsbanken.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'ORKLA_SB',
    'Orkla Sparebank',
    'orkla.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://orklasparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'RINDAL_SB',
    'Rindal Sparebank',
    'rindal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://rindalsbanken.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'ROMSDAL_SB',
    'Romsdalsbanken',
    'romsdal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://romsdalsbanken.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'ROROS',
    'Rørosbanken',
    'roros.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://rorosbanken.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SANDNES_SB',
    'Sandnes Sparebank',
    'sandnes.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://sandnes-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SELBU_SB',
    'Selbu Sparebank',
    'selbu.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://selbusparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SKAGERRAK_SB',
    'Skagerrak Sparebank',
    'skagerrak.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://skagerraksparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SKUE_SB',
    'Skue Sparebank',
    'skue.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://skuesparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SOGN',
    'Sogn Sparebank',
    'sogn.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://sognbank.no//aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SOKNEDAL_SB',
    'Soknedal Sparebank',
    'soknedal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://soknedal-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SPAREBANKEN_DIN',
    'Sparebanken DIN',
    'sparebanken_din.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://sparebankendin.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SB_NARVIK',
    'Sparebanken Narvik',
    'sparebanken_narvik.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://sn.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'STADSBYGD_SB',
    'Stadsbygd Sparebank',
    'stadsbygd.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://stbank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'STROMMEN_SB',
    'Strømmen Sparebank',
    'strommen.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://strommensparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SUNNDAL_SB',
    'Sunndal Sparebank',
    'sunndal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://sunndal-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SURNADAL_SB',
    'Surnadal Sparebank',
    'surnadal.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://bank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'TINN_SB',
    'Tinn Sparebank',
    'tinn.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://tinnbank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'TOLGA_SB',
    'Tolga-Os Sparebank',
    'tolga.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://tos.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'TOTENS_SB',
    'Totens Sparebank',
    'toten.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://totenbanken.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'TROGSTAD_SB',
    'Trøgstad Sparebank',
    'trogstad.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://tsbank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'TYSNES_SB',
    'Tysnes Sparebank',
    'tysnes.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://tysnes-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'VALDRES_SB',
    'Valdres Sparebank',
    'valdres.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://valdressparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'VALLE_SB',
    'Valle Sparebank',
    'valle.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://valle-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'VEKSELBANKEN',
    'Vekselbanken',
    'vekselbanken.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://vekselbanken.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'ORLAND_SB',
    'Ørland Sparebank',
    'orland.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://orland-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'ORSKOG_SB',
    'Ørskog Sparebank',
    'orskog.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://orskogsparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'OSTRE_AGDER_SB',
    'Østre Agder Sparebank',
    'ostre_agder.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://oasparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'AFJORD_SB',
    'Åfjord Sparebank',
    'aafjord.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://afjord-sparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SPAREBANK_68',
    'Sparebank 68 Grader Nord',
    '68nord.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://68nord.no//aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SPAREBANK_68',
    'Lofoten Sparebank',
    '68nord.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://68nord.no//aktuelt/bankid-paa-mobil'
  )
];

export const BankList: BankVo[] = [
  // DNB: hasSubMembership is set to false, but if user is redirected to signicat solution they will go to subBank page
  new BankVo(
    'DNB',
    'DNB Bank ASA',
    'dnb.png',
    'dnb-color.svg',
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    'https://m.dnb.no/kundeservice/privat/bankidmobil.html'
  ),
  new BankVo(
    'BATE',
    'Bate boligbyggelag (DNB)',
    'dnb.png',
    'dnb-color.svg',
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'SYKEPLEIERFORBUND_DNB',
    'Norsk Sykepleierforbund (DNB)',
    'dnb.png',
    'dnb-color.svg',
    true,
    false,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'TOBB',
    'TOBB (DNB)',
    'dnb.png',
    'dnb-color.svg',
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'USBL',
    'USBL (DNB)',
    'dnb.png',
    'dnb-color.svg',
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'SYKEPLEIERNE',
    'SYKEPLEIERNE (DNB)',
    'dnb.png',
    'dnb-color.svg',
    true,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'NORDEA',
    'Nordea',
    'nordea.png',
    'nordea-color.svg',
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.nordea.no/privat/kundeservice/slik-gjor-du/slik-kommer-du-i-gang-med-bankid-pa-mobil.html'
  ),
  new BankVo(
    'YS_NORDEA_DIRECT',
    'YS (Nordea Direct)',
    'nordea_direct.png',
    'nordea-color.svg',
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'SPAREBANK_1',
    'SpareBank 1',
    'sparebanken1v2.png',
    'sparebank1-color.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_BV',
    'SpareBank 1 BV',
    'sparebanken1v2.png',
    'sparebank1-bv.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_GUDBRANDSDAL',
    'SpareBank 1 Gudbrandsdal',
    'sparebanken1v2.png',
    'sparebank1-gudbrandsdal.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_HALLINGDAL_VALDRES',
    'SpareBank 1 Hallingdal Valdres',
    'sparebanken1v2.png',
    'sparebank1-hallingdalvaldres.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_LOM_OG_SKJAK',
    'SpareBank 1 Lom og Skjåk',
    'sparebanken1v2.png',
    'sparebank1-lomsjak.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_MODUM',
    'SpareBank 1 Modum',
    'sparebanken1v2.png',
    'sparebank1-modum.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_NORD_NORGE',
    'SpareBank 1 Nord-Norge',
    'sparebanken1v2.png',
    'sparebank1-nordnorge.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_NORDMORE',
    'SpareBank 1 Nordmøre',
    'sparebanken1v2.png',
    'sparebank1-nordmore.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_RINGERIKE_HADELAND',
    'SpareBank 1 Ringerike Hadeland',
    'sparebanken1v2.png',
    'sparebank1-ringerikehadeland.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_SMN',
    'SpareBank 1 SMN',
    'sparebanken1v2.png',
    'sparebank1-smn.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_SR_BANK',
    'SpareBank 1 SR-Bank',
    'sparebanken1v2.png',
    'sparebank1-srbank.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_SORE_SUNNMORE',
    'SpareBank 1 Søre Sunnmøre',
    'sparebanken1v2.png',
    'sparebank1-soresunnmore.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_TELEMARK',
    'SpareBank 1 Telemark',
    'sparebanken1v2.png',
    'sparebank1-telemark.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_OSTFOLD_AKERSHUS',
    'SpareBank 1 Østfold Akershus',
    'sparebanken1v2.png',
    'sparebank1-ostfoldakershus.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_OSTLANDET',
    'SpareBank 1 Østlandet',
    'sparebanken1v2.png',
    'sparebank1-ostlandet.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  new BankVo(
    'SPAREBANK_1_HELGELAND',
    'SpareBank 1 Helgeland',
    'sparebanken1v2.png',
    'sparebank1-helgeland.svg',
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://www.sparebank1.no/nb/bank/privat/kundeservice/mobil/hvordan-bestiller-jeg-bankid-pa-mobil.html'
  ),
  ...eikaBanks
];

export const MissingBankList: BankVo[] = [
  new BankVo(
    'BOLIGKREDITT',
    'Boligkreditt.no (Sparebanken Øst Boligkreditt AS)',
    'boligkreditt.png',
    null,
    false,
    true,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'BN_BANK',
    'BN Bank ASA',
    'bn.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'BULDER',
    'Bulder Bank (Sparebanken Vest)',
    'bulder.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    null
  ),
  new BankVo(
    'CULTURA',
    'Cultura Sparebank',
    'cultura.png',
    null,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'DIN_BANK',
    'Din Bank (Sparebanken Øst)',
    'dinbank.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'ETNE_SB',
    'Etne Sparebank',
    'etne.png',
    'etne_sb.svg',
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    null
  ),
  new BankVo(
    'FANA_SB',
    'Fana Sparebank',
    'fana.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'FLEKKEFJORD_SB',
    'Flekkefjord Sparebank',
    'flekkefjord.png',
    'flekkefjord_sb.svg',
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    null
  ),
  new BankVo(
    'HAUGESUND_SB',
    'Haugesund Sparebank',
    'haugesund.png',
    'haugesund_sb.svg',
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    null
  ),
  new BankVo(
    'KLP',
    'KLP Banken AS',
    'klp.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    null
  ),
  new BankVo(
    'KRAFTBANK',
    'Kraft Bank ASA',
    'kraft.png',
    null,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    null
  ),

  new BankVo(
    'LANDKREDITT',
    'Landkreditt Bank AS',
    'landkreditt.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'LILLESANDS_SB',
    'Lillesands Sparebank',
    'lillesands.png',
    'lillesand_sb.svg',
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    null
  ),
  new BankVo(
    'LUSTER_SB',
    'Luster Sparebank',
    'luster.png',
    'luster_sb.svg',
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    null
  ),
  new BankVo(
    'NORDAX',
    'Nordax Bank AB (publ)',
    'nordax.png',
    null,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'NORDEA_DIRECT',
    'Nordea Direct',
    'nordea_direct.png',
    'nordea_direct.svg',
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    true,
    false,
    null
  ),
  new BankVo(
    'NAL_NORDEA_DIRECT',
    'NAL (Nordea Direct)',
    'nordea_direct.png',
    null,
    false,
    false,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'UNIO_NORDEA_DIRECT',
    'UNIO (Nordea Direct)',
    'nordea_direct.png',
    null,
    false,
    false,
    false,
    true,
    false,
    false,
    true,
    true,
    false,
    false,
    null
  ),
  new BankVo(
    'NYBYGGER',
    'Nybygger.no (Sparebanken Øst)',
    'nybygger.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'OBOS_BANKEN',
    'OBOS-banken AS',
    'obos.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'OSLO_PENSJON',
    'Oslo Pensjonsforsikring AS',
    'oslopensjon.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'SBANKEN',
    'Sbanken ASA',
    'sbanken.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    null
  ),
  new BankVo(
    'SKUDENES_SB',
    'Skudenes & Aakra Sparebank',
    'skudenes.png',
    'skudenes_sb.svg',
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    null
  ),
  new BankVo(
    'SB_SOGNFJORDANE',
    'Sparebanken Sogn og Fjordane',
    'sogn_og_fjordane.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'SB_SOR',
    'Sparebanken Sør',
    'sparebanken_sor.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'SB_VEST',
    'Sparebanken Vest',
    'sparebanken_vest.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'SPAREBANKEN_OST',
    'Sparebanken Øst',
    'sparebanken_ost.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'SPARESKILLINGSBANKEN',
    'Spareskillingsbanken',
    'spareskillingsbanken.png',
    'spareskillingsbanken.svg',
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    null
  ),
  new BankVo(
    'STATENS_PENSJONSKASSE',
    'Statens pensjonskasse',
    'statenspensjonskasse.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'STOREBRAND',
    'Storebrand Bank ASA',
    'storebrand.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'SOGNE_SB',
    'Søgne og Greipstad Sparebank',
    'sognegreipstad.png',
    'sogne_sb.jpg',
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    null
  ),
  new BankVo(
    'VOSS_SB',
    'Voss Sparebank',
    'voss.png',
    'voss_sb.svg',
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    null
  ),
  new BankVo(
    'SB_MORE',
    'Sparebanken Møre',
    'more.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'HUSBANKEN',
    'Husbanken',
    'husbanken.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    null
  ),
  new BankVo(
    'DANSKE_BANK',
    'Danske Bank',
    'danske.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    true,
    false,
    null
  )
];

export const TinkBanks: BankVo[] = [
  new BankVo(
    'HANDELSBANKEN',
    'Handelsbanken NUF',
    'handelsbanken.png',
    null,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    null
  )
];

// These banks have merged into other banks. see RM-415 @ Jira
export const LegacyBanks: BankVo[] = [
  new BankVo(
    'SKUE_SB',
    'Hønefoss Sparebank',
    'skue.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://skuesparebank.no/aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SPAREBANK_68',
    'Ofoten Sparebank',
    '68nord.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://68nord.no//aktuelt/bankid-paa-mobil'
  ),
  new BankVo(
    'SPAREBANK_68',
    'Harstad Sparebank',
    '68nord.png',
    null,
    true,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    'https://68nord.no//aktuelt/bankid-paa-mobil'
  )
];

export class BankUtils {
  static getBankByName(bankName: string): BankVo | null {
    const name = bankName.toUpperCase();
    const banks = [...BankList, ...MissingBankList, ...TinkBanks];
    for (const bank of banks) {
      if (bank.name === name) {
        return bank;
      }
    }
    return null;
  }

  static getBankLogoUrl(
    bankName: string | null,
    basePath = '../../../assets/img/banks-logo/'
  ): string {
    if (bankName === null) {
      return basePath + 'round/default-bank-icon.png';
    }
    const bank = this.getBankByName(bankName);
    if (bank?.logo) {
      if (bank.logo.indexOf('.svg') > -1) {
        return basePath + 'svg/' + bank.logo;
      } else {
        return basePath + 'round/' + bank.logo;
      }
    } else {
      return basePath + 'wide/' + bank?.icon;
    }
  }

  static getBankPngIcon(
    bankName: string,
    basePath = '../../../assets/img/banks-logo/'
  ): string {
    const bank = this.getBankByName(bankName);
    if (bank !== null) {
      return basePath + 'round/' + bank.icon;
    } else {
      return basePath + 'round/default-bank-icon.png';
    }
  }

  static isEikaBank(bankName: string): boolean {
    return eikaBanks
      .map((bank) => {
        return bank.name;
      })
      .includes(bankName);
  }

  static isTinkBank(bankName: string): boolean {
    return TinkBanks.map((bank) => {
      return bank.name;
    }).includes(bankName);
  }
}

// Interface for Swedish site
export interface BankOfferPreview {
  averageRemainingYears: number;
  bankEmail: string | null;
  bankName: string;
  clientInfo: ClientInfo;
  commonDebt: number;
  effectiveRate: number;
  ltv: number;
  nominalRate: number;
  offerUrl: string | null;
  productName: string;
  propertyValue: number;
  totalOutstandingDebt: number;
}

export interface ClientInfo {
  address: string | null;
  age: number;
  email: string;
  name: string;
  phone: string;
  ssn: string;
  zip: string;
}

export interface OffersBank {
  offers: {
    id: string;
    name: string;
    rate: number;
  }[];
}

export interface NewOffers {
  bankName: string;
  clientId: number;
  effectiveRate: number;
  savingsFirstYear: number;
  totalSavings: number;
}

export interface BankOfferLocations {
  [region: string]: {
    [city: string]: string[];
  };
}

export interface offerOfficeDto {
  region: string;
  city: string;
  officeAddress: string;
}
