export const BANKID_STATUS = {
  PROCESS_STARTED: 'PROCESS_STARTED',
  PASSPHRASE_CONFIRM: 'PASSPHRASE_CONFIRM',
  PASSPHRASE_CONFIRM_SUCCESS: 'PASSPHRASE_CONFIRM_SUCCESS',
  PASSPHRASE_CONFIRM_FAIL: 'PASSPHRASE_CONFIRM_FAIL',
  CRAWLER_ERROR: 'CRAWLER_ERROR',
  CRAWLER_RESULT: 'CRAWLER_RESULT',
  LOANS_PERSISTED: 'LOANS_PERSISTED',

  // CONFIRM_PASSPHRASE: 'CONFIRM_PASSPHRASE',
  // BANKID_APPROVED : 'BANKID_APPROVED',
  // BANKID_TIMEOUT: 'BANKID_TIMEOUT',
  // DOCUMENTS_DOWNLOADED: 'DOCUMENTS_DOWNLOADED',
  // OFFER_DETAILS: 'OFFER_DETAILS',
  // PROVIDED_DATA_NOT_VALID: 'PROVIDED_DATA_NOT_VALID',
  // ERROR_HAPPENED: 'ERROR_HAPPENED',
  // NO_SUCH_INSURANCE_TYPE_SUPPORTED: 'NO_SUCH_INSURANCE_TYPE_SUPPORTED',
  // NO_DOCUMENTS_AVAILABLE: 'NO_DOCUMENTS_AVAILABLE',
  // BANK_ID_WASNT_APPROVED: 'BANK_ID_WASNT_APPROVED',
  // BANK_ID_FAILED_CONNECTION: 'BANK_ID_FAILED_TO_CONNECT_WITH_USER_APP',
  // GJENSIDIGE_CONFIRM_INFO: 'GJENSIDIGE_CONFIRM_INFO',
  // TRYG_CONFIRM_INFO: 'CONFIRM_USER_EMAIL_PHONE',
  // CONFIRM_INFO_INVALID: 'CONFIRM_USER_EMAIL_PHONE_NOT_SUCCESFULL',
  // FRENDE_CONFIRM_INFO: 'FRENDE_CONFIRM_INFO',
  // FRENDE_FEED_CONFIRM_INFO: 'FRENDE_FEED_CONFIRM_INFO',
  // IF_CONFIRM_INFO: 'IF_CONFIRM_INFO',
  // USER_IS_NOT_COMPANY_CUSTOMER: 'USER_IS_NOT_COMPANY_CUSTOMER',
  // NO_ACTIVE_INSURANCES_FOUND: 'NO_ACTIVE_INSURANCES_FOUND',
  // CROWLER_FRONTEND_PROBLEM: 'CRAWLED_FRONTEND_HAS_PROBLEM',
  // CAN_NOT_PARSE_PROVIDED_DOCUMENTS: 'PDF2DATA_CAN_NOT_PARSE_PROVIDED_DOCUMENTS',
  // NO_CRAWLERS_FOR_SESSION_EXIST: 'NO_CRAWLERS_FOR_SESSION_EXIST'
};

export const IDENTIFICATION_TIMEOUT_TIME = 15;

export const BANKID_TIMEOUT_TIME = 90;

export const RECONNECTION_TIME = 3000;

export const RECONNECTION_TRIES = 10;

export const PING_TIME = 15000;
