export const OFFER_SAVINGS_TYPE = {
  NO_SAVINGS: 'NO_SAVINGS',
  SAVINGS_FIRST_YEAR_BETWEEN_0_AND_2000: 'SAVINGS_FIRST_YEAR_BETWEEN_0_AND_2000',
  SAVINGS_FIRST_YEAR_BETWEEN_2000_AND_6000: 'SAVINGS_FIRST_YEAR_BETWEEN_2000_AND_6000',
  SAVINGS_FIRST_YEAR_BETWEEN_6000_AND_10000: 'SAVINGS_FIRST_YEAR_BETWEEN_6000_AND_10000',
  SAVINGS_FIRST_YEAR_GREATER_10000: 'SAVINGS_FIRST_YEAR_GREATER_10000'
};

export const AGGREGATED_RATE_TYPE = {
  FIXED: 'FIXED',
  FLOATING: 'FLOATING',
  MIX_FIXED_FLOATING: 'MIX_FIXED_FLOATING'
};

export const AGGREGATED_LOAN_TYPE = {
  CREDIT_LINE: 'CREDIT_LINE',
  MIX_D_C: 'MIX_D_C',
  MIX_C_O: 'MIX_C_O',
  MIX_D_C_O: 'MIX_D_C_O'
};
