export const LOAN_STATE_MAP = {
  NO_LOANS: 'NO_LOANS',
  NO_OFFERS: 'NO_OFFERS',
  SAVINGS_FIRST_YEAR_BELOW_0: 'SAVINGS_FIRST_YEAR_BELOW_0',
  SAVINGS_FIRST_YEAR_BETWEEN_3000_AND_0: 'SAVINGS_FIRST_YEAR_BETWEEN_3000_AND_0',
  SAVINGS_FIRST_YEAR_GREATER_3000: 'SAVINGS_FIRST_YEAR_GREATER_3000'
};
